import React,{useMemo,useState}from'react';
export interface ReporterArticleSummary{id:string;title:string;state:'DRAFT'|'PENDING_REVIEW'|'ON_HOLD'|'APPROVED'|'PUBLISHED'|'ARCHIVED';updatedAt?:string;reviewComment?:string;leadImageUrl?:string;viewCount?:number;topic?:string;subtitle?:string;body?:string}
const label:Record<string,string>={DRAFT:'초안',PENDING_REVIEW:'승인 대기',ON_HOLD:'보류',APPROVED:'승인 완료 · APPROVED',PUBLISHED:'게시 완료',ARCHIVED:'보관'};
export function ReporterDesk({articles,onCreate,onOpen}:{articles:ReporterArticleSummary[];onCreate:()=>void;onOpen:(id:string)=>void}){
 const[state,setState]=useState(''),[topic,setTopic]=useState(''),[views,setViews]=useState('all');
 const topics=useMemo(()=>Array.from(new Set(articles.map(a=>a.topic||'General'))).sort(),[articles]);
 const filtered=useMemo(()=>articles.filter(a=>{const vc=a.viewCount||0;return(!state||a.state===state)&&(!topic||(a.topic||'General')===topic)&&(views==='all'||(views==='popular'?vc>=10:views==='viewed'?vc>0:vc===0))}),[articles,state,topic,views]);
 return <main className="editor-page"><header className="editor-head"><div><p className="eyebrow">MY STORIES</p><h1>내 글</h1><p>작성 중인 기사와 퍼블리시 진행 상태를 확인하세요.</p></div><button className="primary-button" onClick={onCreate}>+ 새 기사</button></header><section className="my-post-filters"><select value={topic} onChange={e=>setTopic(e.target.value)}><option value="">모든 주제</option>{topics.map(t=><option key={t}>{t}</option>)}</select><select value={views} onChange={e=>setViews(e.target.value)}><option value="all">모든 조회수</option><option value="popular">10회 이상</option><option value="viewed">조회 있음</option><option value="zero">조회 없음</option></select><select value={state} onChange={e=>setState(e.target.value)}><option value="">모든 글 상태</option>{Object.entries(label).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select><span>{filtered.length}건</span></section><section className="story-grid">{filtered.map(a=><button className="story-card story-card-rich" onClick={()=>onOpen(a.id)} key={a.id}>{a.leadImageUrl?<img className="story-thumb" src={a.leadImageUrl} alt=""/>:<div className="story-thumb empty">NO IMAGE</div>}<div className="story-card-body"><div className="story-card-meta"><span className={`workflow-badge ${a.state.toLowerCase()}`}>{label[a.state]||a.state}</span><span>{a.topic||'General'}</span><span>조회 {(a.viewCount||0).toLocaleString()}</span></div><h3>{a.title||'제목 없는 기사'}</h3><small>{a.updatedAt?new Date(a.updatedAt).toLocaleString():'-'}</small>{a.state==='ON_HOLD'&&a.reviewComment&&<p className="hold-comment">관리자 의견 · {a.reviewComment}</p>}</div></button>)}{filtered.length===0&&<div className="empty-state">조건에 맞는 기사가 없습니다.</div>}</section></main>
}
