import test from'node:test';import assert from'node:assert/strict';import{canUseMode}from'../src/auth/roles';import{assertArticleTransition,canTransitionArticle}from'../server/services/articleWorkflow';import{buildClusterRecoveryPlan,buildRestoreMap}from'../server/services/storyRecovery';import{buildStoryAgentCommand,parseStoryAgentResult}from'../server/services/storyAgentProtocol';import{validateArticleImageUpload}from'../server/services/imageUploadPolicy';import{canEditOwnedArticle,requireAdmin}from'../server/services/authz';import{actorFromClaims}from'../server/services/authSession';import{validateParsedArticle}from'../server/sources/protocol/defaultValidation';import{buildEditorialPublicArticle,extractMarkdownImageUrls}from'../server/services/editorialArticle';
test('role presentation modes never grant admin mode to editor/member',()=>{assert.equal(canUseMode('ADMIN','reader'),true);assert.equal(canUseMode('ADMIN','reporter'),true);assert.equal(canUseMode('EDITOR','admin'),false);assert.equal(canUseMode('MEMBER','reporter'),false)});
test('server authorization is independent from presentation mode',()=>{assert.equal(canEditOwnedArticle({id:'e1',role:'EDITOR'},'e1'),true);assert.equal(canEditOwnedArticle({id:'e1',role:'EDITOR'},'e2'),false);assert.equal(canEditOwnedArticle({id:'a1',role:'ADMIN'},'e2'),true);assert.throws(()=>requireAdmin({id:'e1',role:'EDITOR'}));assert.equal(actorFromClaims({sub:'u1',role:'not-admin'})?.role,'MEMBER')});
test('publishing requires admin approval',()=>{assert.equal(canTransitionArticle('PENDING_REVIEW','PUBLISHED','EDITOR'),false);assert.equal(canTransitionArticle('PENDING_REVIEW','APPROVED','ADMIN'),true);assert.equal(canTransitionArticle('APPROVED','PUBLISHED','ADMIN'),true);assert.throws(()=>assertArticleTransition('DRAFT','PUBLISHED','ADMIN'))});
test('cluster recovery is bounded and reversible',()=>{const rows=Array.from({length:180},(_,i)=>({articleId:`a${i}`,clusterId:`c${i}`}));const plan=buildClusterRecoveryPlan(rows);assert.equal(plan.associations.length,150);assert.equal(buildRestoreMap(plan).get('a0'),'c0');assert.throws(()=>buildClusterRecoveryPlan(rows,151))});
test('story agent result is batch-bound and rejects unknown articles',()=>{const command=buildStoryAgentCommand('batch-1',[{articleId:'a1',title:'Example'}]);assert.match(command,/BATCH_ID: batch-1/);const result=parseStoryAgentResult(JSON.stringify({protocolVersion:1,batchId:'batch-1',assignments:[{articleId:'a1',clusterKey:'event-1',confidence:.8}]}),'batch-1',new Set(['a1']));assert.equal(result.assignments[0].clusterKey,'event-1');assert.throws(()=>parseStoryAgentResult(JSON.stringify({protocolVersion:1,batchId:'batch-1',assignments:[{articleId:'other',clusterKey:null}]}),'batch-1',new Set(['a1'])))});
test('image policy rejects unsupported or oversized files',()=>{assert.doesNotThrow(()=>validateArticleImageUpload({mimetype:'image/webp',size:1024,originalname:'news.webp'}));assert.throws(()=>validateArticleImageUpload({mimetype:'image/svg+xml',size:1024,originalname:'x.svg'}));assert.throws(()=>validateArticleImageUpload({mimetype:'image/jpeg',size:11*1024*1024,originalname:'huge.jpg'}))});
test('source protocol validation rejects fabricated or malformed essentials',()=>{const base={sourceId:'s',sourceUrl:'https://source.test/a',canonicalUrl:'https://source.test/a',originalLanguage:'en',originalTitle:'Title',originalBody:'Body',publishedAt:'2026-10-05T12:00:00Z',portalCategoryId:'General',imageUrls:[],contentBlocks:[]};assert.equal(validateParsedArticle(base).ok,true);assert.equal(validateParsedArticle({...base,publishedAt:'unknown'}).ok,false);assert.equal(validateParsedArticle({...base,canonicalUrl:'javascript:bad'}).ok,false)});

test('editorial publish extracts markdown images and leaves AI category undefined',()=>{const body='Intro\n\n![hero](https://cdn.test/a.webp)\ntext\n![second](https://cdn.test/b.jpg)';assert.deepEqual(extractMarkdownImageUrls(body),['https://cdn.test/a.webp','https://cdn.test/b.jpg']);const row=buildEditorialPublicArticle({articleId:'e1',title:'Title',body,author:'Editor',publishedAt:'2026-10-07T00:00:00Z'});assert.equal(row.source_id,'editorial');assert.equal(row.portal_category_id,null);assert.equal(row.topic,null);assert.equal(row.lead_image_url,'https://cdn.test/a.webp');assert.deepEqual(row.image_urls,['https://cdn.test/a.webp','https://cdn.test/b.jpg']);assert.equal(row.processing_status,'RAW')});
