import { Router } from 'express';
import { db } from '../db/database.js';
import { isSupabaseReady, fetchArticlesDirectly, fetchArticleDetailDirectly } from '../db/supabaseStore.js';
const router = Router();
function normalizeTopicCategory(cat:string=''){const c=cat.toLowerCase();if(c.includes('tech')||c.includes('ai'))return'AI/Tech';if(c.includes('educat')||c.includes('school')||c.includes('learn')||c.includes('acad'))return'Education';if(c.includes('econ')||c.includes('estate')||c.includes('invest')||c.includes('business'))return'Economy/RealEstate';if(c.includes('sport'))return'Sports';if(c.includes('politic')||c.includes('gov'))return'Politics';if(c.includes('volunt')||c.includes('communit')||c.includes('charity'))return'Volunteers';if(c.includes('nature')||c.includes('liv')||c.includes('environ')||c.includes('cultur'))return'Nature/Living';return cat;}
function getArticleRegion(a:any){if(a.region)return a.region.toLowerCase();const src=db.core.sources[a.source_id];if(src?.region)return src.region.toLowerCase();const cat=(a.portal_category_id||'').toLowerCase();return['rwanda','korea','africa','world'].includes(cat)?cat:'rwanda';}
router.get('/',async(req,res)=>{const q=req.query as any;const list=(v:any,lower=false)=>v?String(v).split(',').map(x=>lower?x.toLowerCase():x).filter(Boolean):[];const regionList=list(q.regions,true),categoryList=list(q.categories),aiStatusList=list(q.aiStatus,true),sourceList=list(q.sources),langList=list(q.languages),excludeCategoryList=list(q.excludeCategories),excludeRegionList=list(q.excludeRegions,true),excludeSourceList=list(q.excludeSources),excludeLangList=list(q.excludeLanguages),searchQuery=q.search?String(q.search).toLowerCase().trim():'';const sort=q.sort||'newest',limit=Number(q.limit||50),offset=Number(q.offset||0),lang=q.lang||'original';if(isSupabaseReady()){try{return res.json(await fetchArticlesDirectly({regions:regionList,categories:categoryList,aiStatus:aiStatusList,sources:sourceList,languages:langList,excludeCategories:excludeCategoryList,excludeRegions:excludeRegionList,excludeSources:excludeSourceList,excludeLanguages:excludeLangList,search:searchQuery,sort,limit,offset,lang}));}catch(err:any){console.warn('[Articles API] Direct Supabase fetch fallback to local:',err?.message||err);}}let all=Object.values(db.core.articles);if(excludeCategoryList.length)all=all.filter(a=>!excludeCategoryList.includes(normalizeTopicCategory(a.portal_category_id))&&!excludeCategoryList.includes(a.portal_category_id));if(excludeRegionList.length)all=all.filter(a=>!excludeRegionList.includes(getArticleRegion(a)));if(excludeSourceList.length)all=all.filter(a=>!excludeSourceList.includes(a.source_id));if(excludeLangList.length)all=all.filter(a=>!excludeLangList.includes(a.original_language.toLowerCase()));if(regionList.length)all=all.filter(a=>regionList.includes(getArticleRegion(a)));if(categoryList.length)all=all.filter(a=>categoryList.includes(normalizeTopicCategory(a.portal_category_id))||categoryList.includes(a.portal_category_id));if(aiStatusList.length)all=all.filter(a=>aiStatusList.includes(a.processing_status==='PROCESSED'?'done':'waiting'));if(sourceList.length)all=all.filter(a=>sourceList.includes(a.source_id));if(langList.length)all=all.filter(a=>langList.includes(a.original_language.toLowerCase()));if(searchQuery)all=all.filter(a=>a.original_title.toLowerCase().includes(searchQuery)||a.original_body.toLowerCase().includes(searchQuery));all.sort((a,b)=>sort==='oldest'?new Date(a.published_at).getTime()-new Date(b.published_at).getTime():new Date(b.published_at).getTime()-new Date(a.published_at).getTime());const total=all.length;const articles=all.slice(offset,offset+limit).map(a=>({...a,displayTitle:a.original_title,displaySubtitle:a.original_subtitle,displaySummary:a.original_subtitle||a.original_body.slice(0,180)+'...',isLocalized:false,relatedStoriesCount:a.story_cluster_id?(db.core.storyClusterArticles[a.story_cluster_id]?.length||0):0,relatedEvents:[],tags:[]}));res.json({total,articles,limit,offset});});
router.post('/group-similar',(_req,res)=>res.status(410).json({success:false,error:'Heuristic grouping is disabled. Use the AI Agent Story Clustering workflow in AI Workspace.'}));
router.get('/:id',async(req,res)=>{if(isSupabaseReady()){try{const detail=await fetchArticleDetailDirectly(req.params.id);if(detail)return res.json({article:detail,localized:{ko:detail.ko,en:detail.en,rw:detail.rw},ko:detail.ko,en:detail.en,rw:detail.rw,similarArticles:[],previousArticles:[],futureArticles:[]});}catch(err:any){console.warn('[Articles API] detail fallback:',err?.message||err);}}const art=db.core.articles[req.params.id];if(!art)return res.status(404).json({error:'Article not found'});res.json({article:art,localized:{ko:db.ko.articles[art.article_id],en:db.en.articles[art.article_id],rw:db.rw.articles[art.article_id]},similarArticles:[],previousArticles:[],futureArticles:[]});});
export default router;
