import{Router}from'express';import{getSupabaseConfig,generateSupabaseDDL,testSupabaseConnection}from'../db/supabase.js';import{fetchBatchGroupsDirectly,fetchUnprocessedBatchGroupsDirectly,fetchGroupArticlesDirectly,fetchUnprocessedGroupArticlesDirectly,fetchArticleDetailDirectly,saveProcessedArticleDirectly}from'../db/supabaseStore.js';const router=Router();
const unprocessed=(v:unknown)=>String(v||'').toLowerCase()==='true';
const groupData=(n:number,u:boolean)=>u?fetchUnprocessedGroupArticlesDirectly(n):fetchGroupArticlesDirectly(n);
async function buildAgentPrompt(n:number,u:boolean){const g=await groupData(n,u),rows=(g.articles||[]).map((a:any)=>`${a.article_id}\t${a.original_title}`).join('\n');return `# ChatGPT 기사 처리 Agent Command\n모드: ${u?'미처리 집중배정':'일반 배정'}\n그룹: #${n}\n아래 기사만 순서대로 처리하세요. 이미 PROCESSED인 기사는 건너뜁니다. 각 기사에 대해 topic을 결정하고 KO/EN/RW 번역·3줄 요약·본문을 완성한 뒤 Supabase에 저장하세요.\n\n${rows}`}
async function buildTopicPrompt(batch:number,u:boolean){const start=(Math.max(1,batch)-1)*5+1,all:any[]=[];for(let n=start;n<start+5;n++){const g=await groupData(n,u);all.push(...(g.articles||[]))}const rows=all.slice(0,150).map((a:any)=>`${a.article_id}\t${a.original_title}`).join('\n');return rows?`# 150개 기사 Topic 재결정\n다음 ${all.slice(0,150).length}개 기사에 대해 표준 영문 Topic을 하나씩 결정하세요. article_id를 변경하지 말고 결과를 Supabase articles.topic에 반영하세요.\n\n${rows}`:''}
router.post('/cluster-similar-articles',(_req,res)=>res.status(410).json({error:'Legacy heuristic clustering is disabled. Use /api/story-agent/batch and validate the agent result before any cluster changes.'}));
router.get('/supabase/status',async(_req,res)=>{const config=getSupabaseConfig(),test=await testSupabaseConnection();res.json({config:{configured:config.configured,url:config.url?`${config.url.slice(0,18)}...`:''},test,ddl:generateSupabaseDDL()})});
router.post('/sync-articles',async(_req,res)=>{try{const test=await testSupabaseConnection();res.json({success:true,count:test.articleCount||0})}catch(err:any){res.status(500).json({success:false,error:err.message})}});router.post('/supabase/config',(_req,res)=>res.status(410).json({error:'Runtime Supabase configuration is environment-only.'}));
router.get('/openapi.json',(req,res)=>res.json({openapi:'3.1.0',info:{title:'News Intelligence MCP API',version:'2.0.0'},servers:[{url:`${req.protocol}://${req.get('host')}`}],paths:{}}));
router.get('/groups',async(req,res)=>{try{res.json(unprocessed(req.query.unprocessed)?await fetchUnprocessedBatchGroupsDirectly():await fetchBatchGroupsDirectly())}catch(err:any){res.status(500).json({error:err.message})}});
router.get('/group/:groupNumber',async(req,res)=>{try{res.json(await groupData(Number(req.params.groupNumber)||1,unprocessed(req.query.unprocessed)))}catch(err:any){res.status(500).json({error:err.message})}});
router.get('/prompt/:groupNumber',async(req,res)=>{try{res.json({prompt:await buildAgentPrompt(Number(req.params.groupNumber)||1,unprocessed(req.query.unprocessed))})}catch(err:any){res.status(500).json({error:err.message})}});
router.get('/topic-prompt/:batchIndex',async(req,res)=>{try{res.json({prompt:await buildTopicPrompt(Number(req.params.batchIndex)||1,unprocessed(req.query.unprocessed))})}catch(err:any){res.status(500).json({error:err.message})}});
router.get('/article/:article_id',async(req,res)=>{const art=await fetchArticleDetailDirectly(req.params.article_id);if(!art)return res.status(404).json({error:'Article not found'});res.json(art)});router.post('/save-article',async(req,res)=>{try{res.json(await saveProcessedArticleDirectly(req.body))}catch(err:any){res.status(500).json({error:err.message})}});
router.post('/rpc',async(req,res)=>{const{jsonrpc,id,method,params}=req.body||{};if(jsonrpc!=='2.0')return res.status(400).json({jsonrpc:'2.0',id,error:{code:-32600,message:'Invalid Request'}});try{if(method==='tools/list')return res.json({jsonrpc:'2.0',id,result:{tools:[{name:'get_batch_groups',inputSchema:{type:'object',properties:{}}},{name:'get_group_articles',inputSchema:{type:'object',properties:{group_number:{type:'number'}},required:['group_number']}},{name:'get_raw_article',inputSchema:{type:'object',properties:{article_id:{type:'string'}},required:['article_id']}},{name:'save_processed_article',inputSchema:{type:'object',properties:{article_id:{type:'string'}},required:['article_id']}}]}});if(method==='tools/call'){const name=params?.name,args=params?.arguments||{};let data:any;if(name==='get_batch_groups')data=await fetchBatchGroupsDirectly();else if(name==='get_group_articles')data=await fetchGroupArticlesDirectly(args.group_number||1);else if(name==='get_raw_article')data=await fetchArticleDetailDirectly(args.article_id);else if(name==='save_processed_article')data=await saveProcessedArticleDirectly(args);else return res.status(400).json({jsonrpc:'2.0',id,error:{code:-32601,message:`Tool ${name} not found`}});return res.json({jsonrpc:'2.0',id,result:{content:[{type:'text',text:JSON.stringify(data)}]}})}return res.status(400).json({jsonrpc:'2.0',id,error:{code:-32601,message:'Method not implemented'}})}catch(error:any){return res.status(500).json({jsonrpc:'2.0',id,error:{code:-32000,message:error.message}})}});export default router;
