import { Router } from 'express';
import { db } from '../db/database.js';
import { getSupabaseClient } from '../db/supabase.js';
import { buildStoryAgentCommand, parseStoryAgentResult, StoryAgentArticle } from '../services/storyAgentProtocol.js';
const router=Router(); const batches=new Map<string,{articleIds:string[];proposed?:ReturnType<typeof parseStoryAgentResult>}>();
async function loadArticles(requested:string[]):Promise<StoryAgentArticle[]>{const client=getSupabaseClient();if(client){let query=client.from('articles').select('article_id,original_title,original_body,source_id,published_at,story_cluster_id').order('published_at',{ascending:false}).limit(150);if(requested.length)query=query.in('article_id',requested.slice(0,150));else query=query.is('story_cluster_id',null);const{data,error}=await query;if(error)throw error;return(data||[]).map((a:any)=>({articleId:a.article_id,title:a.original_title||'',body:a.original_body||'',sourceId:a.source_id,publishedAt:a.published_at,existingClusterId:a.story_cluster_id||null}));}const ids=requested.length?requested.filter(id=>!!db.core.articles[id]).slice(0,150):Object.values(db.core.articles).filter(a=>!a.story_cluster_id).slice(0,150).map(a=>a.article_id);return ids.map(id=>db.core.articles[id]).filter(Boolean).map(a=>({articleId:a.article_id,title:a.original_title,body:a.original_body,sourceId:a.source_id,publishedAt:a.published_at,existingClusterId:a.story_cluster_id||null}));}
router.post('/batch',async(req,res)=>{try{const requested:string[]=Array.isArray(req.body?.articleIds)?req.body.articleIds:[];const articles=await loadArticles(requested);const articleIds=articles.map(a=>a.articleId);const batchId=`STORY-${Date.now().toString(36)}`;batches.set(batchId,{articleIds});res.json({batchId,count:articles.length,command:buildStoryAgentCommand(batchId,articles)});}catch(error){res.status(500).json({error:error instanceof Error?error.message:'Batch creation failed'});}});
router.post('/batch/:batchId/validate',(req,res)=>{const batch=batches.get(req.params.batchId);if(!batch)return res.status(404).json({error:'Batch not found'});try{const proposed=parseStoryAgentResult(typeof req.body?.result==='string'?req.body.result:JSON.stringify(req.body?.result),req.params.batchId,new Set(batch.articleIds));batch.proposed=proposed;res.json({valid:true,proposed});}catch(error){res.status(400).json({valid:false,error:error instanceof Error?error.message:'Invalid result'});}});
export default router;
