import React from'react';
export interface ReaderArticleCard{id:string;title:string;summary?:string;imageUrl?:string;source?:string;sourceId?:string;publishedLabel?:string;publishedAt?:string;originalLanguage?:string;category?:string;sourceUrl?:string}
export function ReaderHome({articles,onOpen}:{articles:ReaderArticleCard[];onOpen:(id:string)=>void}){
  const categorized=articles.filter(a=>Boolean(a.category));
  const groups=Array.from(new Set(categorized.map(a=>a.category!))).slice(0,8).map(category=>({category,items:categorized.filter(a=>a.category===category).slice(0,5)})).filter(g=>g.items.length);
  return <div>
    {groups.length>0&&<section className="flex snap-x snap-mandatory overflow-x-auto [scrollbar-width:none]">{groups.map(g=>{const[lead,...four]=g.items;return <div key={g.category} className="w-full shrink-0 snap-center p-4">
      <button onClick={()=>onOpen(lead.id)} className="relative block h-[50svh] min-h-[360px] w-full overflow-hidden rounded-3xl bg-black text-left !text-white shadow-sm">{lead.imageUrl&&<img src={lead.imageUrl} alt="" className="absolute inset-0 h-full w-full object-cover opacity-75"/>}<div className="absolute inset-0 bg-gradient-to-t from-black via-black/55 to-black/10"/><div className="absolute inset-x-0 bottom-0 p-6 pt-24 !text-white [text-shadow:0_2px_14px_rgba(0,0,0,.65)]"><span className="text-xs font-black uppercase tracking-widest !text-white">{g.category}</span><h1 className="mt-2 text-3xl font-black leading-tight !text-white">{lead.title}</h1></div></button>
      {four.length>0&&<div className="mt-3 grid grid-cols-4 gap-2">{four.map(a=><button key={a.id} onClick={()=>onOpen(a.id)} className="min-w-0 overflow-hidden rounded-xl border border-[var(--border)] bg-[var(--bg-card)] text-left"><div className="aspect-[4/3] bg-slate-100">{a.imageUrl&&<img src={a.imageUrl} alt="" className="h-full w-full object-cover" loading="lazy"/>}</div><div className="p-1.5"><h3 className="line-clamp-2 text-[11px] font-bold leading-[1.3] sm:text-xs">{a.title}</h3></div></button>)}</div>}
    </div>})}</section>}
    <section className="p-4"><h2 className="mb-2 text-xl font-black">최신 기사</h2><div className="divide-y divide-[var(--border)]">{articles.map(a=><button key={a.id} onClick={()=>onOpen(a.id)} className="grid min-h-28 w-full grid-cols-[1fr_104px] gap-3 py-4 text-left"><div>{a.category&&<span className="text-[11px] font-black uppercase text-[var(--accent)]">{a.category}</span>}<h3 className="mt-1 font-bold leading-snug">{a.title}</h3><p className="mt-2 text-xs opacity-60">{[a.source,a.publishedLabel].filter(Boolean).join(' · ')}</p></div>{a.imageUrl?<img src={a.imageUrl} alt="" className="h-20 w-[104px] rounded-lg object-cover" loading="lazy"/>:<div className="h-20 rounded-lg bg-slate-100"/>}</button>)}</div></section>
  </div>
}
