import React,{useEffect,useMemo,useRef,useState}from'react';
import{api}from'../lib/api';import type{PortalTheme,SourceInfo}from'../types';import type{UserProfile}from'../auth/roles';
import{MobileReaderShell}from'./MobileReaderShell';import{ReaderHome,ReaderArticleCard}from'./ReaderHome';import{ReaderArticle,ReaderArticleDetail}from'./ReaderArticle';import{ReaderControlDock}from'./ReaderControlDock';
const PAGE=30;const themes:PortalTheme[]=['BLACK','BLUE','PINK','RAINBOW'];
const localeFor=(language:string,originalLanguage?:string)=>{const lang=language==='original'?(originalLanguage||'en'):language;return lang==='ko'?'ko-KR':lang==='rw'?'rw-RW':'en-US'};
const formatDate=(value:string|undefined,language:string,originalLanguage?:string,withTime=false)=>{if(!value)return undefined;const d=new Date(value);if(Number.isNaN(d.getTime()))return undefined;return new Intl.DateTimeFormat(localeFor(language,originalLanguage),withTime?{year:'numeric',month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'}:{year:'numeric',month:'long',day:'numeric'}).format(d)};
const cleanCategory=(a:any)=>{const raw=a.topic||a.portal_category_id;if(!raw||raw==='undefined'||raw==='null'||(a.source_id==='editorial'&&raw==='General'))return undefined;return String(raw)};
export function ReaderApp({onWrite,profile,onLogin,onLogout,onProfile,onMyPosts,onAdmin}:{onWrite?:()=>void;profile?:UserProfile|null;onLogin?:()=>void;onLogout?:()=>void;onProfile?:()=>void;onMyPosts?:()=>void;onAdmin?:()=>void}={}){
  const[cards,setCards]=useState<ReaderArticleCard[]>([]),[selected,setSelected]=useState<ReaderArticleDetail|null>(null),[selectedId,setSelectedId]=useState<string|null>(null),[loading,setLoading]=useState(true),[loadingMore,setLoadingMore]=useState(false),[hasMore,setHasMore]=useState(true),[controls,setControls]=useState(false),[search,setSearch]=useState(''),[category,setCategory]=useState(''),[source,setSource]=useState(''),[sources,setSources]=useState<SourceInfo[]>([]),[language,setLanguage]=useState(()=>localStorage.getItem('reader_language')||'original'),[theme,setTheme]=useState<PortalTheme>(()=>(localStorage.getItem('reader_theme')as PortalTheme)||'BLACK'),[compact,setCompact]=useState(false);
  const sentinel=useRef<HTMLDivElement>(null),detailCache=useRef(new Map<string,ReaderArticleDetail>()),inflight=useRef(new Map<string,Promise<ReaderArticleDetail>>());
  const mapCard=(a:any):ReaderArticleCard=>({id:a.article_id,title:a.displayTitle||a.title||a.original_title||'Untitled',summary:a.displaySummary||a.summary||a.original_subtitle,imageUrl:a.lead_image_url,source:a.source_name||a.source_id,sourceId:a.source_id,publishedAt:a.published_at,originalLanguage:a.original_language,publishedLabel:formatDate(a.published_at,language,a.original_language,false),category:cleanCategory(a),sourceUrl:a.source_url});
  const fetchPage=async(reset=false)=>{reset?setLoading(true):setLoadingMore(true);try{const offset=reset?0:cards.length;const res=await api.getArticles({sort:'newest',limit:PAGE,offset,search,categories:category,sources:source,lang:language});const next=(res.articles||[]).map(mapCard);setCards(p=>reset?next:[...p,...next.filter(n=>!p.some(x=>x.id===n.id))]);setHasMore(offset+next.length<(res.total||0)&&next.length>0)}finally{setLoading(false);setLoadingMore(false)}};
  useEffect(()=>{void api.getSources().then(r=>setSources(r.sources||[])).catch(()=>setSources([]))},[]);
  useEffect(()=>{detailCache.current.clear();inflight.current.clear();void fetchPage(true)},[category,source,language]);
  useEffect(()=>{document.documentElement.setAttribute('data-theme',theme);document.documentElement.className=document.documentElement.className.replace(/theme-\w+/g,'').trim();document.documentElement.classList.add(`theme-${theme.toLowerCase()}`);localStorage.setItem('reader_theme',theme);localStorage.setItem('reader_language',language)},[theme,language]);
  useEffect(()=>{const el=sentinel.current;if(!el)return;const io=new IntersectionObserver(e=>{if(e[0].isIntersecting&&hasMore&&!loading&&!loadingMore&&!selected)void fetchPage(false)},{rootMargin:'500px'});io.observe(el);return()=>io.disconnect()},[cards.length,hasMore,loading,loadingMore,selected,search,category,source,language]);
  const loadDetail=(id:string)=>{const key=`${language}:${id}`,cached=detailCache.current.get(key);if(cached)return Promise.resolve(cached);const running=inflight.current.get(key);if(running)return running;const promise=api.getArticleById(id).then(res=>{const a=res.article||res,loc=language!=='original'?(res.localized?.[language]||a[language]):null,detail:ReaderArticleDetail={id,title:loc?.title||loc?.localized_title||a.displayTitle||a.original_title||'Untitled',subtitle:loc?.subtitle||a.original_subtitle,summary:loc?.summary||a.summary||a.ai_summary||a.original_subtitle,body:loc?.body_markdown||loc?.body||a.original_body||'',imageUrl:a.lead_image_url,author:a.author,source:a.source_name||a.source_id,publishedLabel:formatDate(a.published_at,language,a.original_language,true),category:cleanCategory(a),sourceUrl:a.source_url};detailCache.current.set(key,detail);inflight.current.delete(key);return detail}).catch(e=>{inflight.current.delete(key);throw e});inflight.current.set(key,promise);return promise};
  const prefetchNeighbors=(id:string)=>{const i=cards.findIndex(a=>a.id===id);[cards[i-1],cards[i+1]].filter(Boolean).forEach(a=>void loadDetail(a.id).catch(()=>{}))};
  const open=async(id:string)=>{const detail=await loadDetail(id);setSelectedId(id);setSelected(detail);prefetchNeighbors(id);window.scrollTo({top:0})};
  const move=async(d:number)=>{const i=cards.findIndex(a=>a.id===selectedId),n=cards[i+d];if(n)await open(n.id)};
  const cats=useMemo(()=>Array.from(new Set(cards.map(a=>a.category).filter((x):x is string=>Boolean(x)))).sort(),[cards]);
  const sourceOptions=useMemo(()=>{const m=new Map<string,string>();for(const s of sources)m.set(s.id,s.name||s.id);m.set('editorial','Editorial');for(const a of cards)if(a.sourceId&&!m.has(a.sourceId))m.set(a.sourceId,a.source||a.sourceId);return [...m.entries()].sort((a,b)=>a[1].localeCompare(b[1]))},[sources,cards]);
  const home=()=>{setSelected(null);setSelectedId(null);window.scrollTo({top:0})};
  return <MobileReaderShell>
    <ReaderControlDock profile={profile||null} onHome={home} onFilter={()=>setControls(v=>!v)} onWrite={onWrite} language={language} onLanguageChange={setLanguage} theme={theme} onThemeChange={setTheme} onLogin={onLogin||(()=>{})} onLogout={onLogout||(()=>{})} onProfile={onProfile||(()=>{})} onMyPosts={onMyPosts||(()=>{})} onAdmin={onAdmin||(()=>{})}/>
    {controls&&!selected&&<form onSubmit={e=>{e.preventDefault();void fetchPage(true)}} className="reader-filter grid grid-cols-2 gap-2 border-b border-[var(--border)] bg-[var(--bg-main)] p-3"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="기사 검색" className="col-span-2 min-h-11 rounded-lg border border-[var(--border)] bg-[var(--bg-card)] px-3"/><select value={category} onChange={e=>setCategory(e.target.value)} className="min-h-11 rounded-lg border border-[var(--border)] bg-[var(--bg-card)] px-2"><option value="">모든 분야</option>{cats.map(c=><option key={c}>{c}</option>)}</select><select value={source} onChange={e=>setSource(e.target.value)} className="min-h-11 rounded-lg border border-[var(--border)] bg-[var(--bg-card)] px-2"><option value="">모든 기사소스</option>{sourceOptions.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><label className="col-span-2 flex min-h-11 items-center gap-2 rounded-lg border border-[var(--border)] px-3"><input type="checkbox" checked={compact} onChange={e=>setCompact(e.target.checked)}/>간단히 보기</label><button className="col-span-2 min-h-11 rounded-lg bg-[var(--accent)] font-bold text-white">적용</button></form>}
    {loading?<p className="p-8 text-center">뉴스를 불러오는 중…</p>:selected?<><button onClick={()=>setSelected(null)} className="mx-4 mt-3 min-h-11 font-bold">← 홈으로</button><ReaderArticle article={selected} onPrevious={cards.findIndex(a=>a.id===selectedId)>0?()=>void move(-1):undefined} onNext={cards.findIndex(a=>a.id===selectedId)<cards.length-1?()=>void move(1):undefined}/></>:<><ReaderHome articles={compact?cards.map(a=>({...a,summary:undefined,imageUrl:undefined})):cards} onOpen={id=>void open(id)}/><div ref={sentinel} className="p-6 text-center text-sm opacity-60">{loadingMore?'기사 불러오는 중…':hasMore?'아래로 스크롤하면 계속 불러옵니다':'마지막 기사입니다'}</div></>}
  </MobileReaderShell>
}
