import { ArticleRecord } from '../db/types.js';
import { getSupabaseClient } from '../db/supabase.js';
import { calculateSimilarity, normalizeTitle } from '../sources/utils/hash.js';
import { getPortalValue, listPortalValues, putPortalValue } from '../db/portalStore.js';
const client=()=>{const c=getSupabaseClient();if(!c)throw new Error('Supabase is not configured.');return c;};
export class DeduplicationService{
 async processArticleDuplicates(article:ArticleRecord){const{data,error}=await client().from('articles').select('*').neq('article_id',article.article_id);if(error)throw error;for(const e of data||[]){const sameUrl=e.canonical_url&&article.canonical_url&&e.canonical_url===article.canonical_url;const sameHash=e.content_hash&&article.content_hash&&e.content_hash===article.content_hash;const near=e.source_id===article.source_id&&calculateSimilarity(e.normalized_title||'',article.normalized_title||'')>=.9&&String(e.published_at).slice(0,10)===String(article.published_at).slice(0,10);if(sameUrl||sameHash||near)return this.assignDuplicateGroup(e,article);}return{isDuplicate:false};}
 private async assignDuplicateGroup(existing:any,incoming:ArticleRecord){const groupId=existing.duplicate_group_id||`DUP-GRP-${Math.random().toString(36).slice(2,9)}`;const group=(await getPortalValue<any>('duplicateGroups',groupId))||{id:groupId,canonicalArticleId:existing.article_id,articleIds:[existing.article_id]};if(!group.articleIds.includes(incoming.article_id))group.articleIds.push(incoming.article_id);await putPortalValue('duplicateGroups',groupId,group);await client().from('articles').update({duplicate_group_id:groupId}).in('article_id',[existing.article_id,incoming.article_id]);incoming.duplicate_group_id=groupId;return{isDuplicate:true,duplicateGroupId:groupId};}
 async findStoryCluster(article:ArticleRecord){const{data,error}=await client().from('articles').select('*').neq('article_id',article.article_id);if(error)throw error;const at=new Date(article.published_at).getTime();for(const other of data||[]){if(Math.abs(at-new Date(other.published_at).getTime())/3600000>96)continue;if(calculateSimilarity(article.normalized_title||'',other.normalized_title||'')>=.55){if(other.story_cluster_id)return other.story_cluster_id;const id=`CLUSTER-${Math.random().toString(36).slice(2,8)}`;await putPortalValue('storyClusters',id,{id,title:other.original_title,representative_article_id:other.article_id,article_count:2,created_at:new Date().toISOString(),updated_at:new Date().toISOString()});await putPortalValue('storyClusterArticles',id,[other.article_id,article.article_id]);await client().from('articles').update({story_cluster_id:id}).in('article_id',[other.article_id,article.article_id]);return id;}}return undefined;}
 async updateArticleRelations(targetArticleIds?:string[]){const{data,error}=await client().from('articles').select('*');if(error)throw error;const all=data||[],scope=targetArticleIds?all.filter(a=>targetArticleIds.includes(a.article_id)):all;let updatedCount=0;for(const art of scope){const similar:string[]=[],previous:string[]=[],future:string[]=[];const at=new Date(art.published_at).getTime(),norm=art.normalized_title||normalizeTitle(art.original_title);for(const other of all){if(other.article_id===art.article_id)continue;const diff=(new Date(other.published_at).getTime()-at)/3600000,sim=calculateSimilarity(norm,other.normalized_title||normalizeTitle(other.original_title));if(sim>=.45||(art.story_cluster_id&&art.story_cluster_id===other.story_cluster_id)){if(diff < -12)previous.push(other.article_id);else if(diff>12)future.push(other.article_id);else similar.push(other.article_id);}}const old=(await getPortalValue<any>('articleRelations',art.article_id))||{similar:[],previous:[],future:[]};const value={similar:[...new Set([...old.similar,...similar])],previous:[...new Set([...old.previous,...previous])],future:[...new Set([...old.future,...future])],cluster_title:old.cluster_title};await putPortalValue('articleRelations',art.article_id,value);updatedCount++;}return{updatedCount,clustersCreated:0};}
}
export const deduplicationService=new DeduplicationService();
