import * as XLSX from 'xlsx';
import AdmZip from 'adm-zip';
import { getSupabaseClient } from '../db/supabase.js';
import { getPortalValue, listPortalValues, listSources, putPortalValue } from '../db/portalStore.js';
import { eventService } from './events.js';

const client=()=>{const c=getSupabaseClient();if(!c)throw new Error('Supabase is not configured.');return c;};
const id=()=>`${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;
const bookBuffer=(wb:XLSX.WorkBook)=>Buffer.from(XLSX.write(wb,{type:'buffer',bookType:'xlsx'}));
const rows=(wb:XLSX.WorkBook,name:string)=>wb.Sheets[name]?XLSX.utils.sheet_to_json<any>(wb.Sheets[name],{defval:''}):[];

export function extractExcelFilesFromUploads(files:{filename:string;buffer:Buffer}[]){const out:{filename:string;buffer:Buffer}[]=[];for(const f of files){if(/\.zip$/i.test(f.filename)){const zip=new AdmZip(f.buffer);for(const e of zip.getEntries())if(!e.isDirectory&&/\.xlsx?$/i.test(e.entryName))out.push({filename:e.entryName,buffer:e.getData()});}else if(/\.xlsx?$/i.test(f.filename))out.push(f);}return out;}

export class DirectExcelService{
 zipCache=new Map<string,{buffer:Buffer;filename:string}>();
 private async articleMap(ids:string[]){if(!ids.length)return new Map<string,any>();const{data,error}=await client().from('articles').select('*').in('article_id',ids);if(error)throw error;return new Map((data||[]).map((a:any)=>[a.article_id,a]));}
 private async localizedMap(ids:string[]){if(!ids.length)return new Map<string,any>();const{data,error}=await client().from('localized_articles').select('*').in('article_id',ids);if(error)throw error;return new Map((data||[]).map((a:any)=>[`${a.lang}:${a.article_id}`,a]));}
 async generateArticleBatchWorkbook(articleIds:string[],batchName?:string,record=true){const [arts,locs,sources]=await Promise.all([this.articleMap(articleIds),this.localizedMap(articleIds),listSources()]);const sourceMap=new Map(sources.map((s:any)=>[s.id,s]));const input=articleIds.map(articleId=>{const a:any=arts.get(articleId);if(!a)return null;const s:any=sourceMap.get(a.source_id);return{article_id:a.article_id,source_id:a.source_id,source_name:s?.name||a.source_id,source_url:a.source_url,published_at:a.published_at,original_language:a.original_language,original_title:a.original_title,original_subtitle:a.original_subtitle||'',original_body:a.original_body||'',topic:a.topic||'General',topic_sub:a.topic_sub||'General',region:a.region||s?.region||''};}).filter(Boolean);const localized=(lang:string)=>input.map((r:any)=>{const l=locs.get(`${lang}:${r.article_id}`)||{};return{article_id:r.article_id,[`title_${lang}`]:l.title||'',[`subtitle_${lang}`]:l.subtitle||'',[`summary_${lang}`]:l.summary||'',[`body_${lang}`]:l.body||'',main_topic:l.topic||r.topic||'',region:r.region||''};});const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(input),'INPUT_ARTICLES');for(const lang of ['ko','en','rw'])XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(localized(lang)),`OUTPUT_${lang.toUpperCase()}`);XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([]),'ARTICLE_TAGS');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([]),'EVENT_CANDIDATES');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([]),'SIMILAR_ARTICLES');const batchId=`BATCH-${id()}`;const filename=`${(batchName||'article-batch').replace(/[^a-zA-Z0-9_-]+/g,'_')}-${batchId}.xlsx`;if(record){await putPortalValue('aiBatches',batchId,{batch_id:batchId,batch_type:'ARTICLE',status:'EXPORTED',article_ids:articleIds,created_at:new Date().toISOString()});if(articleIds.length){const{error}=await client().from('articles').update({processing_status:'EXPORTED',updated_at:new Date().toISOString()}).in('article_id',articleIds).neq('processing_status','PROCESSED');if(error)throw error;}}return{buffer:bookBuffer(wb),filename,batchId};}
 async generateMultiArticleBatchZip(articleIds:string[],batchName:string,chunkSize=25,targetTotal=2500,onProgress?:(current:number,total:number,message:string)=>void){const ids=articleIds.slice(0,targetTotal);const chunks:Array<string[]>=[];for(let i=0;i<ids.length;i+=chunkSize)chunks.push(ids.slice(i,i+chunkSize));const zip=new AdmZip();for(let i=0;i<chunks.length;i++){const x=await this.generateArticleBatchWorkbook(chunks[i],`${batchName}-${i+1}`,false);zip.addFile(x.filename,x.buffer);onProgress?.(i+1,chunks.length,`Generated ${i+1}/${chunks.length}`);}const batchId=`BATCH-${id()}`,zipFilename=`${batchName.replace(/[^a-zA-Z0-9_-]+/g,'_')}-${batchId}.zip`,buffer=zip.toBuffer();this.zipCache.set(batchId,{buffer,filename:zipFilename});await putPortalValue('aiBatches',batchId,{batch_id:batchId,batch_type:'ARTICLE_MULTI',status:'EXPORTED',article_ids:ids,created_at:new Date().toISOString()});if(ids.length){const{error}=await client().from('articles').update({processing_status:'EXPORTED',updated_at:new Date().toISOString()}).in('article_id',ids).neq('processing_status','PROCESSED');if(error)throw error;}return{batchId,zipFilename,fileCount:chunks.length,totalArticles:ids.length};}
 async previewArticleWorkbook(fileBuffer:Buffer){const wb=XLSX.read(fileBuffer,{type:'buffer'});const localized=['ko','en','rw'].flatMap(lang=>rows(wb,`OUTPUT_${lang.toUpperCase()}`).map(r=>String(r.article_id||'')).filter(Boolean));const ids=[...new Set(localized)];const map=await this.articleMap(ids);const validArticleIds=ids.filter(x=>map.has(x));return{totalArticles:validArticleIds.length,koCount:rows(wb,'OUTPUT_KO').filter(r=>r.article_id).length,enCount:rows(wb,'OUTPUT_EN').filter(r=>r.article_id).length,rwCount:rows(wb,'OUTPUT_RW').filter(r=>r.article_id).length,eventCandidatesCount:rows(wb,'EVENT_CANDIDATES').filter(r=>r.has_event==='YES'||r.event_name).length,tagsCount:rows(wb,'ARTICLE_TAGS').length,relationsCount:rows(wb,'SIMILAR_ARTICLES').length,errors:ids.length?[]:['No article IDs found'],warnings:ids.filter(x=>!map.has(x)).map(x=>`Article ID ${x} does not exist.`),validArticleIds};}
 async previewMultipleWorkbooks(files:{filename:string;buffer:Buffer}[]){const ps=await Promise.all(files.map(async f=>({filename:f.filename,p:await this.previewArticleWorkbook(f.buffer)})));return{totalFiles:files.length,totalArticles:ps.reduce((n,x)=>n+x.p.totalArticles,0),koCount:ps.reduce((n,x)=>n+x.p.koCount,0),enCount:ps.reduce((n,x)=>n+x.p.enCount,0),rwCount:ps.reduce((n,x)=>n+x.p.rwCount,0),eventCandidatesCount:ps.reduce((n,x)=>n+x.p.eventCandidatesCount,0),tagsCount:ps.reduce((n,x)=>n+x.p.tagsCount,0),relationsCount:ps.reduce((n,x)=>n+x.p.relationsCount,0),errors:ps.flatMap(x=>x.p.errors.map(e=>`[${x.filename}] ${e}`)),warnings:ps.flatMap(x=>x.p.warnings.map(e=>`[${x.filename}] ${e}`)),fileSummaries:ps.map(x=>({filename:x.filename,totalArticles:x.p.totalArticles,validCount:x.p.validArticleIds.length,status:x.p.errors.length?'WARNING':'READY',errors:x.p.errors}))};}
 async importArticleWorkbook(fileBuffer:Buffer){const preview=await this.previewArticleWorkbook(fileBuffer);if(!preview.validArticleIds.length)return{success:false,importedCount:0,relationsCount:0,errors:preview.errors};const wb=XLSX.read(fileBuffer,{type:'buffer'}),now=new Date().toISOString(),out:any[]=[];for(const lang of ['ko','en','rw'])for(const r of rows(wb,`OUTPUT_${lang.toUpperCase()}`)){const article_id=String(r.article_id||'');if(!preview.validArticleIds.includes(article_id))continue;out.push({article_id,lang,title:r[`title_${lang}`]||'',subtitle:r[`subtitle_${lang}`]||null,summary:r[`summary_${lang}`]||null,body:r[`reparagraphed_body_${lang}`]||r[`body_${lang}`]||'',topic:r.main_topic||'General',topic_sub:r.topic_sub||'General',processed_at:now});}if(out.length){const{error}=await client().from('localized_articles').upsert(out,{onConflict:'article_id,lang'});if(error)throw error;}const complete=new Set<string>();for(const aid of preview.validArticleIds)if(['ko','en','rw'].every(l=>out.some(r=>r.article_id===aid&&r.lang===l&&r.body)))complete.add(aid);for(const aid of preview.validArticleIds){const topic=out.find(r=>r.article_id===aid)?.topic;const patch:any={processing_status:complete.has(aid)?'PROCESSED':'PARTIAL',updated_at:now};if(topic)patch.topic=topic;patch.topic_sub='General';const{error}=await client().from('articles').update(patch).eq('article_id',aid);if(error)throw error;}for(const r of rows(wb,'ARTICLE_TAGS')){const aid=String(r.article_id||'');if(!preview.validArticleIds.includes(aid))continue;const names=String(r.tags||r.tag_names||'').split(/[,;|]/).map((x:string)=>x.trim()).filter(Boolean);for(const name of names){const key=name.toLowerCase().replace(/\s+/g,'-'),cid=`TAG-${key}`;await putPortalValue('tagConcepts',cid,{tag_concept_id:cid,key});for(const lang of ['ko','en','rw']){await putPortalValue(`${lang}_tags`,cid,{tag_concept_id:cid,name:r[`tag_${lang}`]||name});const col=`${lang}_articleTags`,current=(await getPortalValue<string[]>(col,aid))||[];await putPortalValue(col,aid,[...new Set([...current,cid])]);}}}for(const er of rows(wb,'EVENT_CANDIDATES'))if((er.has_event==='YES'||er.event_name)&&er.event_name){const result=await eventService.createOrMergeEvent({canonical_name:er.event_name,subtitle:er.event_subtitle,start_date:er.start_date||now.slice(0,10),source_article_id:er.article_id} as any);for(const lang of ['ko','en','rw'])await putPortalValue(`${lang}_eventText`,result.event.event_id,{event_id:result.event.event_id,canonical_name:er[`event_name_${lang}`]||er.event_name,subtitle:er[`event_subtitle_${lang}`]||er.event_subtitle});}return{success:true,importedCount:preview.validArticleIds.length,relationsCount:0,errors:[]};}
 async importMultipleWorkbooks(files:{filename:string;buffer:Buffer}[]){let importedCount=0,relationsCount=0;const errors:string[]=[],fileSummaries:any[]=[];for(const f of files)try{const r=await this.importArticleWorkbook(f.buffer);importedCount+=r.importedCount;relationsCount+=r.relationsCount;fileSummaries.push({filename:f.filename,importedCount:r.importedCount,status:r.success?'IMPORTED':'FAILED'});errors.push(...r.errors.map(e=>`[${f.filename}] ${e}`));}catch(e:any){errors.push(`[${f.filename}] ${e.message}`);fileSummaries.push({filename:f.filename,importedCount:0,status:'ERROR'});}return{success:importedCount>0,totalFiles:files.length,importedCount,relationsCount,errors,fileSummaries};}
 async generateEventsExportWorkbook(eventIds?:string[]){const[events,ko,en,rw,links]=await Promise.all([listPortalValues<any>('events'),listPortalValues<any>('ko_eventText'),listPortalValues<any>('en_eventText'),listPortalValues<any>('rw_eventText'),listPortalValues<string[]>('eventArticles')]);const selected=(eventIds?eventIds.map(x=>events[x]):Object.values(events)).filter(Boolean);const data=selected.map((e:any)=>({event_id:e.event_id,event_name:e.canonical_name,event_name_ko:ko[e.event_id]?.canonical_name||'',event_name_en:en[e.event_id]?.canonical_name||e.canonical_name,event_name_rw:rw[e.event_id]?.canonical_name||'',subtitle:e.subtitle||'',start_date:e.start_date,end_date:e.end_date||'',status:e.status||'',related_article_ids:(links[e.event_id]||[]).join(',')}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(data),'EVENTS');return{buffer:bookBuffer(wb),filename:`events-${Date.now()}.xlsx`};}
 async generateEventUrlWorkbook(urlIds:string[]){const urls=await listPortalValues<any>('eventUrls');const data=urlIds.map(x=>urls[x]).filter(Boolean);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(data),'EVENT_URLS');const batchId=`BATCH-${id()}`;await putPortalValue('aiBatches',batchId,{batch_id:batchId,batch_type:'EVENT_URL',status:'EXPORTED',url_ids:urlIds,created_at:new Date().toISOString()});return{buffer:bookBuffer(wb),filename:`event-urls-${batchId}.xlsx`,batchId};}
 async generateIntegratedArticleWorkbook(articleIds:string[],topicTitle:string){const arts=await this.articleMap(articleIds);const data=articleIds.map(x=>arts.get(x)).filter(Boolean).map((a:any)=>({article_id:a.article_id,title:a.original_title,body:a.original_body,source_url:a.source_url}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(data),'SOURCE_ARTICLES');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{title:topicTitle||'',subtitle:'',body:'',topic:'General',topic_sub:'General'}]),'INTEGRATED_OUTPUT');const batchId=`BATCH-${id()}`;await putPortalValue('aiBatches',batchId,{batch_id:batchId,batch_type:'INTEGRATED',status:'EXPORTED',article_ids:articleIds,created_at:new Date().toISOString()});return{buffer:bookBuffer(wb),filename:`integrated-${batchId}.xlsx`,batchId};}
}
export const excelService=new DirectExcelService();
