import * as cheerio from 'cheerio';
import { normalizeUrl } from '../sources/utils/url.js';
import { decodeHtmlEntities, normalizeWhitespace } from '../sources/utils/html.js';
import { getPortalValue, listPortalValues, putPortalValue } from '../db/portalStore.js';

export class EventInboxService {
  async addUrls(rawInput:string):Promise<{added:number;existing:number;invalid:number}>{const lines=rawInput.split(/[\r\n,]+/).map(s=>s.trim()).filter(Boolean);const current=await listPortalValues<any>('eventUrls');let added=0,existing=0,invalid=0;for(const line of lines){if(!line.startsWith('http://')&&!line.startsWith('https://')){invalid++;continue;}const normalized=normalizeUrl(line);if(!normalized){invalid++;continue;}if(Object.values(current).some((u:any)=>u.url===normalized)){existing++;continue;}const id=`EURL-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;const item={id,url:normalized,status:'QUEUED',created_at:new Date().toISOString(),updated_at:new Date().toISOString()};current[id]=item;await putPortalValue('eventUrls',id,item);added++;}return{added,existing,invalid};}
  async fetchUrlText(urlId:string):Promise<boolean>{const item:any=await getPortalValue('eventUrls',urlId);if(!item)return false;item.status='FETCHING';item.updated_at=new Date().toISOString();await putPortalValue('eventUrls',urlId,item);const controller=new AbortController();const timeoutId=setTimeout(()=>controller.abort(),15000);try{const response=await fetch(item.url,{signal:controller.signal,headers:{'User-Agent':'Mozilla/5.0 (Event Intelligence Bot)','Accept':'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'}});if(!response.ok)throw new Error(`HTTP ${response.status}`);const html=await response.text();const $=cheerio.load(html);$('script, style, nav, footer, header, noscript, svg, iframe').remove();item.fetched_title=decodeHtmlEntities($('h1, title, meta[property="og:title"]').first().text().trim()||'Event Page');item.fetched_text=decodeHtmlEntities(normalizeWhitespace($('body').text())).slice(0,30000);item.status='READY';item.updated_at=new Date().toISOString();await putPortalValue('eventUrls',urlId,item);return true;}catch(err:any){item.status='ERROR';item.error_message=err.message||'Failed to fetch URL';item.updated_at=new Date().toISOString();await putPortalValue('eventUrls',urlId,item);return false;}finally{clearTimeout(timeoutId);}}
  async fetchAllQueued():Promise<{processed:number;successCount:number}>{const queued=Object.values(await listPortalValues<any>('eventUrls')).filter((u:any)=>u.status==='QUEUED') as any[];let successCount=0;for(const q of queued){if(await this.fetchUrlText(q.id))successCount++;await new Promise(r=>setTimeout(r,400));}return{processed:queued.length,successCount};}
}
export const eventInboxService=new EventInboxService();
