import { EventRecord } from '../db/types.js';
import { fetchArticlesDirectly } from '../db/supabaseStore.js';
import { getPortalValue, getSettings, listPortalValues, putPortalValue, removePortalValue } from '../db/portalStore.js';
import { calculateSimilarity, normalizeTitle } from '../sources/utils/hash.js';
export class EventService{
 private score(a:any,b:any){const n=calculateSimilarity(normalizeTitle(a.canonical_name||''),normalizeTitle(b.canonical_name||''));const dateBonus=a.start_date&&a.start_date===b.start_date?0.2:0;return Math.min(1,n+dateBonus);}
 async createOrMergeEvent(data:Partial<EventRecord>):Promise<{event:EventRecord;status:'created'|'merged'|'candidate_queued'}>{const events=await listPortalValues<EventRecord>('events'),settings=await getSettings();let best:any=null,score=0;for(const e of Object.values(events)){const s=this.score(data,e);if(s>score){best=e;score=s;}}if(best&&score>=Number(settings.eventAutoMergeThreshold??.95)){if((data as any).source_article_id){const ids=(await getPortalValue<string[]>('eventArticles',best.event_id))||[];if(!ids.includes((data as any).source_article_id)){ids.push((data as any).source_article_id);await putPortalValue('eventArticles',best.event_id,ids);}}return{event:best,status:'merged'};}const id=`EVT-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;const event:any={...data,event_id:id,canonical_name:data.canonical_name||'Untitled Event',start_date:data.start_date||new Date().toISOString().slice(0,10),all_day:data.all_day??!data.start_time,timezone:data.timezone||settings.defaultTimezone||'Africa/Kigali',status:data.status||'ACTIVE',created_at:new Date().toISOString(),updated_at:new Date().toISOString()};await putPortalValue('events',id,event);if((data as any).source_article_id)await putPortalValue('eventArticles',id,[(data as any).source_article_id]);if(best&&score>=Number(settings.eventReviewThreshold??.7)){const cid=`EMC-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`;await putPortalValue('eventMatchCandidates',cid,{id:cid,source_event_id:id,target_event_id:best.event_id,score,status:'PENDING',created_at:new Date().toISOString()});return{event,status:'candidate_queued'};}return{event,status:'created'};}
 async mergeEvents(sourceId:string,targetId:string,candidateId?:string){const[source,target]=await Promise.all([getPortalValue<any>('events',sourceId),getPortalValue<any>('events',targetId)]);if(!source||!target)return false;const[a,b]=await Promise.all([getPortalValue<string[]>('eventArticles',sourceId),getPortalValue<string[]>('eventArticles',targetId)]);await putPortalValue('eventArticles',targetId,[...new Set([...(b||[]),...(a||[])])]);const hid=`EMH-${Date.now().toString(36)}`;await putPortalValue('eventMergeHistory',hid,{id:hid,canonicalEventId:targetId,mergedEvent:source,timestamp:new Date().toISOString()});await removePortalValue('events',sourceId);await removePortalValue('eventArticles',sourceId);if(candidateId){const c=await getPortalValue<any>('eventMatchCandidates',candidateId);if(c){c.status='MERGED';await putPortalValue('eventMatchCandidates',candidateId,c);}}return true;}
 async rejectCandidate(id:string){const c=await getPortalValue<any>('eventMatchCandidates',id);if(!c)return false;c.status='REJECTED';await putPortalValue('eventMatchCandidates',id,c);return true;}
 async deleteEvent(id:string){if(!await getPortalValue('events',id))return false;await Promise.all(['events','eventArticles','ko_eventText','en_eventText','rw_eventText','ko_eventTags','en_eventTags','rw_eventTags'].map(c=>removePortalValue(c,id)));const cs=await listPortalValues<any>('eventMatchCandidates');await Promise.all(Object.entries(cs).filter(([,c]:any)=>c.source_event_id===id||c.target_event_id===id).map(([k])=>removePortalValue('eventMatchCandidates',k)));return true;}
 async deduplicateAndLinkEvents(){const events=Object.values(await listPortalValues<any>('events'));let mergedCount=0;for(let i=0;i<events.length;i++)for(let j=i+1;j<events.length;j++)if(this.score(events[i],events[j])>=.95&&await this.mergeEvents(events[j].event_id,events[i].event_id))mergedCount++;let linkedArticlesCount=0;const fresh=Object.values(await listPortalValues<any>('events')),arts=(await fetchArticlesDirectly({limit:1000,offset:0})).articles;for(const e of fresh){const ids=(await getPortalValue<string[]>('eventArticles',e.event_id))||[];for(const a of arts){if(!ids.includes(a.article_id)&&calculateSimilarity(normalizeTitle(a.original_title||''),normalizeTitle(e.canonical_name||''))>=.55){ids.push(a.article_id);linkedArticlesCount++;}}await putPortalValue('eventArticles',e.event_id,ids);}return{mergedCount,linkedArticlesCount};}
}
export const eventService=new EventService();
