import { IntegratedArticleRecord } from '../db/types.js';
import { fetchArticleDetailDirectly } from '../db/supabaseStore.js';
import { listPortalValues, putPortalValue } from '../db/portalStore.js';
export interface SentenceTraceInput{sentenceIndex:number;sentenceText:string;sourceArticleId:string;sourceFragment:string;}
export class IntegratedArticleService{
  async saveIntegratedArticle(data:{title:string;subtitle?:string;body:string;topic:string;sourceArticleIds:string[];sentences?:SentenceTraceInput[]}):Promise<IntegratedArticleRecord>{if(!data.sourceArticleIds?.length)throw new Error('At least one source article is required.');const intId=`INT-ART-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;const now=new Date().toISOString();const record:IntegratedArticleRecord={integrated_article_id:intId,title:data.title,subtitle:data.subtitle,body:data.body,topic:data.topic,topic_sub:'General',source_article_ids:data.sourceArticleIds,created_at:now,updated_at:now};await putPortalValue('integratedArticles',intId,record);const traces=data.sentences?.length?data.sentences:data.body.split(/(?<=[.?!])\s+/).filter(s=>s.trim().length>10).map((sentenceText,i)=>({sentenceIndex:i+1,sentenceText,sourceArticleId:data.sourceArticleIds[i%data.sourceArticleIds.length],sourceFragment:''}));for(const st of traces){const sentId=`SENT-${intId}-${st.sentenceIndex}`;await putPortalValue('integratedSentences',sentId,{sentence_id:sentId,integrated_article_id:intId,sentence_index:st.sentenceIndex,sentence_text:st.sentenceText});const article:any=st.sourceArticleId?await fetchArticleDetailDirectly(st.sourceArticleId):null;const srcId=`ISRC-${sentId}-1`;await putPortalValue('integratedSentenceSources',srcId,{id:srcId,sentence_id:sentId,source_article_id:st.sourceArticleId,source_title:article?.original_title||'Source Reference',source_url:article?.source_url,source_fragment:st.sourceFragment||(article?.original_body||'').slice(0,180)+(article?.original_body?'...':'')});}return record;}
  async getSentenceTraces(integratedArticleId:string){const[sentencesMap,sourcesMap]=await Promise.all([listPortalValues<any>('integratedSentences'),listPortalValues<any>('integratedSentenceSources')]);const sentences=Object.values(sentencesMap).filter((s:any)=>s.integrated_article_id===integratedArticleId).sort((a:any,b:any)=>a.sentence_index-b.sentence_index);const sources=Object.values(sourcesMap);return sentences.map((sent:any)=>({...sent,sources:sources.filter((src:any)=>src.sentence_id===sent.sentence_id)}));}
}
export const integratedArticleService=new IntegratedArticleService();
