-- Membership + editorial approval workflow. Additive only; no data deletion.
create table if not exists newsroom_profiles (
  user_id text primary key,
  email text,
  display_name text,
  avatar_url text,
  provider text,
  role text not null default 'MEMBER' check (role in ('MEMBER','EDITOR','ADMIN')),
  status text not null default 'ACTIVE' check (status in ('ACTIVE','SUSPENDED')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists newsroom_article_revisions (
  revision_id text primary key,
  article_id text not null,
  author_id text not null,
  title text not null,
  subtitle text,
  body_markdown text not null,
  source_category text not null default 'Editorial · News',
  original_language text not null default 'ko' check (original_language in ('ko','en','rw')),
  workflow_state text not null default 'DRAFT' check (workflow_state in ('DRAFT','PENDING_REVIEW','ON_HOLD','APPROVED','PUBLISHED','ARCHIVED')),
  review_note text,
  created_at timestamptz not null default now()
);
create index if not exists idx_newsroom_revisions_article on newsroom_article_revisions(article_id,created_at desc);
create index if not exists idx_newsroom_revisions_author on newsroom_article_revisions(author_id,created_at desc);
create table if not exists newsroom_publish_history (
  id bigint generated by default as identity primary key,
  article_id text not null,
  revision_id text,
  action text not null,
  actor_user_id text,
  from_status text,
  to_status text,
  comment text,
  created_at timestamptz not null default now()
);
create index if not exists idx_publish_history_article on newsroom_publish_history(article_id,created_at desc);
create table if not exists newsroom_images (image_id text primary key,article_id text,uploaded_by text not null,storage_url text not null,alt text,caption text,credit text,created_at timestamptz not null default now());
create table if not exists newsroom_audit_events (event_id text primary key,actor_id text not null,action text not null,target_type text not null,target_id text not null,before_json jsonb,after_json jsonb,created_at timestamptz not null default now());
create index if not exists idx_newsroom_audit_target on newsroom_audit_events(target_type,target_id,created_at desc);
create or replace function public.handle_new_newsroom_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.newsroom_profiles(user_id,email,display_name,avatar_url,provider,role,status) values(new.id::text,new.email,coalesce(new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'name'),new.raw_user_meta_data->>'avatar_url',coalesce(new.raw_app_meta_data->>'provider','email'),'MEMBER','ACTIVE') on conflict(user_id) do update set email=excluded.email,avatar_url=coalesce(public.newsroom_profiles.avatar_url,excluded.avatar_url),provider=coalesce(public.newsroom_profiles.provider,excluded.provider),updated_at=now(); return new; end $$;
do $$ begin if not exists(select 1 from pg_trigger where tgname='on_auth_user_created_newsroom') then create trigger on_auth_user_created_newsroom after insert or update of email,raw_user_meta_data,raw_app_meta_data on auth.users for each row execute function public.handle_new_newsroom_user(); end if; end $$;
insert into public.newsroom_profiles(user_id,email,display_name,avatar_url,provider,role,status)
select id::text,email,coalesce(raw_user_meta_data->>'full_name',raw_user_meta_data->>'name'),raw_user_meta_data->>'avatar_url',coalesce(raw_app_meta_data->>'provider','email'),'MEMBER','ACTIVE' from auth.users
on conflict(user_id) do nothing;
alter table newsroom_profiles enable row level security;
alter table newsroom_article_revisions enable row level security;
alter table newsroom_publish_history enable row level security;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('newsroom-images','newsroom-images',true,10485760,array['image/jpeg','image/png','image/webp']) on conflict(id) do nothing;
